spring:
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 500ms
      auto-offset-reset: latest

server:
  port: 8081